#define DISABLE			0x00000000
#define ENABLE			0x00000001

#define OPT_GUARD_EVENTS_LOG			(DISABLE)
#define OPT_CIPHER_EVENTS_LOG			(DISABLE)
#define OPT_LOW_PT_EVENTS_LOG			(DISABLE)
#define OPT_OPCODE_PRINT_LOG			(DISABLE)
#define OPT_SEND_STRINGS_LOG			(DISABLE)
#define OPT_DISCORD_EVENTS_LOG			(DISABLE)

#define OPT_ENABLED(OPTION) (OPTION & ENABLE)
